/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

module.exports = function(grunt) {
	var projectFile = grunt.file.readJSON('project.json');
	var assetsPath = projectFile.root + '/' + projectFile.assets;
	var assetsSource = projectFile.source;
	var buildScripts = './' + assetsSource + '/coreFAB/buildScripts/';
	var vars = {
		packageFile: grunt.file.readJSON('package.json'),
		projectFile: projectFile,
		root: projectFile.root,
		watch: projectFile.watch,
		assetsPath: projectFile.root + '/' + projectFile.assets,
		assetsSource: assetsSource,
		enabledJsComponents: projectFile.enabledJsComponents,
		conf: {
			root: projectFile.root,
			assetsPath: assetsPath,
			assetsSource: assetsSource,
			bsFiles: {
				src: [
					assetsPath + '/css/style.min.css',
					assetsPath + '/js/lib/**/*.js',
					assetsPath + '/js/**/*.js'
				]
			},
			bsOptions: {
				watchTask: true,
				proxy: projectFile.proxy,
				ghostMode: {
					clicks: false,
					forms: false,
					scroll: false,
					links: false
				},
				open: 'local',
				notify: false
			},
			lessCompress: projectFile.lessCompress,
			lessFiles: {},
			jsFiles: {},
			sourceMaps: projectFile.sourceMaps
		}
	};

	// Delete files and cache
	vars = require(buildScripts + '01-cleanUp.js')(grunt, vars);

	// Configure watch and proxy
	vars = require(buildScripts + '02-watchConfg.js')(grunt, vars);

	// Configure Less
	vars = require(buildScripts + '03-lessConfig.js')(grunt, vars);

	// Configure JS
	vars = require(buildScripts + '04-jsConfig.js')(grunt, vars);

	// Configure Build Modules
	vars = require(buildScripts + '05-buildModuleConfig.js')(grunt, vars);

	// Configure Compile Modules
	vars = require(buildScripts + '06-compileModuleConfig.js')(grunt, vars);

	// Configure File Copy
	vars = require(buildScripts + '07-copyFiles.js')(grunt, vars);

	// Configure version file
	vars = require(buildScripts + '08-versionConfig.js')(grunt, vars);

	// Initialize grunt config
	vars = require(buildScripts + '09-initConfig.js')(grunt, vars);

	// Load NPM Tasks
	grunt.loadNpmTasks('grunt-contrib-less');
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-jscs');
	grunt.loadNpmTasks('grunt-notify');
	grunt.loadNpmTasks('grunt-browser-sync');

	// Register grunt default task
	grunt.registerTask('default', [
		'less',
		'uglify',
		'notify:less',
		'notify:uglify',
		'browserSync',
		'watch'
	]);

	// Register grunt compile task
	grunt.registerTask('compile', [
		'less',
		'uglify'
	]);
};
