/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

(function(F, W, D) {
	'use strict';

	// Supports touch variable
	var support;

	/**
	 * Run check
	 *
	 * called once on demand to populate varible
	 */
	var runCheck = function() {
		support = 'ontouchstart' in W ||
			W.DocumentTouch && D instanceof W.DocumentTouch ||
			W.navigator.maxTouchPoints > 0 ||
			W.navigator.msMaxTouchPoints > 0;
	};

	// Create a FAB object for touch functions
	F.touch = {
		/**
		 * Does the browser support touch?
		 *
		 * @return {bool}
		 */
		support: function() {
			if (support === undefined) {
				runCheck();
			}

			return support;
		}
	};
})(window.STOCKPILE, window, document);
