/*============================================================================*\
	DO NOT EDIT THIS FILE. THIS IS A CORE FILE.
/*============================================================================*/

(function(F) {
	'use strict';

	// Run F functions
	var runFAB = function() {
		var hasRun = [];

		// Make sure everything is ready
		if (! F.ready) {
			setTimeout(function() {
				runFAB();
			}, 100);

			return;
		}

		// Run Auto Initializers
		F.fn.autoInit.forEach(function(fnName) {
			F[fnName].init();

			hasRun.push(fnName);
		});

		// Run any init function requested by exec
		F.exec.forEach(function(fnName) {
			if (hasRun.indexOf(fnName) < 0) {
				F[fnName].init();

				hasRun.push(fnName);
			}
		});

		// Run the controller
		if (F.controller) {
			// Check if an array for this pageType has been defined
			var pageTypeArray = F.controller[F.get('pageType')];

			if (pageTypeArray) {
				pageTypeArray.forEach(function(fnName) {
					if (hasRun.indexOf(fnName) < 0) {
						F[fnName].init();

						hasRun.push(fnName);
					}
				});
			}
		}
	};

	// Run initialization on DOM ready state
	$(function() {
		runFAB();
	});
})(window.STOCKPILE);
